name: Test
on:
  push
jobs:
  test1:
    name: ${{ matrix.os }}-no-defender
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2019
          - windows-2022
    steps:
    - run: fsutil 8dot3name query
      shell: powershell
    - run: fsutil 8dot3name set 1
      shell: powershell
    - run: Set-MpPreference -DisableRealtimeMonitoring $true
      shell: powershell
    - run: |
        Get-Date
        $c = (Join-Path (Get-Location).Path '.github\t.cmd')
        "$c"
        Get-Date
      shell: powershell
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        repository: cue-lang/cue
        ref: d16b5758c12d752c439a78f51baabace69268af7
        fetch-depth: 0
    - run: Get-WinEvent @{ProviderName='Microsoft-Windows-Windows Defender'}
      shell: powershell

  test2:
    name: ${{ matrix.os }}-defender
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-2019
          - windows-2022
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        repository: cue-lang/cue
        ref: d16b5758c12d752c439a78f51baabace69268af7
        fetch-depth: 0
    - run: Get-WinEvent @{ProviderName='Microsoft-Windows-Windows Defender'}
      shell: powershell